parent_config: submodules/ios-tooling/SwiftLint/.swiftlint_base.yml
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - {{NAME}}SampleApp/Pods
included:
  - {{NAME}}
  - {{NAME}}SampleApp
