name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, unlabeled]

concurrency: 
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
  build-and-test:
    timeout-minutes: 30
    name: Build and test
    if: |
      github.event_name != 'pull_request' ||
      (
        !contains(github.event.pull_request.labels.*.name, format('ci{0} none', ':')) &&
        (github.event.action != 'unlabeled' || github.event.label.name == format('ci{0} none', ':'))
      )
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACTIONS_PAT }}
          submodules: recursive

      - name: Run Pod Tests
        uses: ./submodules/ios-tooling/gh-actions/run-pod-tests
        with:
          ssh-key: ${{ secrets.ACTIONS_SSH_AGENT_KEY }}
          failed-snapshots-dir: submodules/snapshots/specs/
